[package]
name = "cminer"
edition = "2018"
version = "0.2.7"
authors = ["Wspsxing <biluohc@qq.com>"]
description = "A cpuminer impl by Rust, supported currency(CKB, ETH, ETC..)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nonblock-logger = { version = "0.1", features = [ "color", "dbg" ] }
ethereum-bigint = "0.2.9"# fake, package name is bigint
serde = { version = "1.0.101", features = ["derive"]}
thiserror = "1.0.5"
structopt = "0.3.3"
anyhow = "1.0.19"
clap = "2.33"
serde_json = "1.0.41"
parking_lot = "0.9"
bytesize = "1.0.0"
faster-hex = "0.4"
eaglesong = "0.1"
ethash = "0.3.1"
ctrlc = "3.1.3"
rayon = "1.2.0"
num_cpus = "1"
digest = "0.8"
rand = "0.7.2"
sha3 = "0.8"

futures = "0.3.1"
tokio = { version = "0.2.2", features = ["rt-core", "tcp", "sync", "time"] }
tokio-util = { version = "0.2.0", features = ["codec"] }
