[package]
name = "cminer"
edition = "2018"
version = "0.2.11"
authors = ["Wspsxing <biluohc@qq.com>"]
description = "A cpuminer impl by Rust, supported currency(CKB, BTC, ETH, ETC..)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[dependencies]
nonblock-logger = { version = "0.1", features = [ "color", "dbg" ] }
bigint = { package = "ethereum-types", version = "0.8" }
serde = { version = "1.0.101", features = ["derive"]}
thiserror = "1.0.5"
structopt = "0.3.9"
anyhow = "1.0.19"
clap = "2.33"
serde_json = "1.0.45"
parking_lot = "0.10"
bytesize = "1.0.0"
faster-hex = "0.4"
eaglesong = "0.1"
bitcoin_hashes = "0.7"
bitcoin = "0.23"
ethash = "0.4.0"
ctrlc = "3.1.3"
rayon = "1.3.0"
num_cpus = "1"
digest = "0.8"
bytes = "0.5"
ring = "0.16"
hex = "0.4.2"
rand = "0.7.2"
sha3 = "0.8"

futures = "0.3.2"
tokio = { version = "0.2.2", features = ["rt-core", "tcp", "sync", "time"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
tokio-rustls = { version = "0.13", features = ["dangerous_configuration"] }
webpki-roots = "0.19.0"
