[package]
name = "cminer"
edition = "2018"
version = "0.2.0"
authors = ["Wspsxing <biluohc@qq.com>"]
description = "A toy cpu-miner for test impl by Rust, suppoted currency(CKB, ETH, ETC..)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nonblock-logger = { version = "0.1", features = [ "color", "dbg" ] }
ethereum-bigint = "0.2.9"# fake, package name is bigint
serde = { version = "1.0.101", features = ["derive"]}
structopt = "0.3.3"
clap = "2.33"
serde_json = "1.0.41"
parking_lot = "0.9"
bytesize = "1.0.0"
faster-hex = "0.4"
eaglesong = "0.1"
ethash = "0.3.1"
ctrlc = "3.1.3"
rayon = "1.2.0"
digest = "0.8"
rand = "0.7.2"
sha3 = "0.8"

futures-preview = "=0.3.0-alpha.19"
pin-utils = "=0.1.0-alpha.4"
tokio = "0.2.0-alpha.6"
futures-core-preview = "=0.3.0-alpha.19"
futures-sink-preview = "=0.3.0-alpha.19"
futures-util-preview = { version = "=0.3.0-alpha.19", features = ["sink"] }
